micronaut:
  application:
    name: revolut-interview
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: jdbc:h2:mem:transfer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase/changelog.xml'

endpoints:
  liquibase:
    enabled: true
    sensitive: false

revolut:
  account-url: '/accounts'
  transfer-url: '/transfers'

